name: Sonarqube Analysis
on:
  push:
    branches:    
      - 'main'
  pull_request:
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.1
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_LOGIN }}
        projectKey: "bobcatpy"
        projectName: "bobcatpy"
        projectVersion: "v1.0.9"